# Generated by Django 4.1.7 on 2023-02-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste1', '0002_alter_produto_descricao_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='indicador_oferta',
            field=models.BooleanField(),
        ),
    ]
