# Generated by Django 4.1.7 on 2023-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste1', '0003_alter_produto_indicador_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
