# Generated by Django 4.1.7 on 2023-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste1', '0004_produto_nome_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=50),
        ),
    ]
