# Generated by Django 4.1.7 on 2023-02-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste1', '0005_alter_produto_nome_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome_produto',
        ),
    ]
